.all-contributorsrc, README.md, src/add-commands.js, src/index.js
BREAKING CHANGE: The queries will now throw a useful message and fail
the test if the queried element is missing.
=> Use `getBy`, not `queryBy`, to fail on missing element

.all-contributorsrc, README.md, cypress/integration/commands.spec.js, src/__tests__/__snapshots__/commands.js.snap, src/index.js
**What**:
Allows things like:
```javascript  
it('queryByText', () => {
cy.queryByText('Button Text').should('exist')
cy.queryByText('Non-existing Button Text').should('not.exist')
})
```
**Why**:
It's a lack of a feature comparing to the DOM-testing-library, and it makes it harder to seamlessly switch between react/cypress without being able to check for elements NONexistence.
**How**:
A bit of a hack, but I think it's better to show a message like that:
(expected null to not exist) , then not allow for checking for nonexistence whatsoever.  Especially since it's just below a log saying "querybysomething value", so it's very easy to understand what's going on. 
If on the other side, the thing we are querying for exists, everything works 100% as expected, with a proper error message.
I've …
=> queryBy* queryAllBy*

.all-contributorsrc, .gitignore, README.md, src/__tests__/__snapshots__/commands.js.snap, src/index.js
**What**:
Make timeout configurable for all query functions through the options object. (Issue #6)
**Why**:
So I don't need to use `cy.wait()` to prevent timeouts from happening.
**How**:
- use timeout from the options object
- make sure that Cypress' timeout is larger, so our error message is used
- make sure Cypress' Command Log doesn't get cluttered when options isn't specified
Other changes
- show example in the docs
- updated outdated snapshot
- ignore .idea folder (JetBrains IDE's)
- added myself to contributers at the request of the contribution guide
**Question**:
Should I add something in the tests to test the timeout? Like some JS code in the html file to dynamically add an element after a certain time?
**Checklist**:
=> feat(timeout): allow to configure the timeout for queries

cypress.json, package.json
**Why**:
Cypress 3 has been released on 5/29/2018 ([changelog](https://docs.cypress.io/guides/references/changelog.html)).
**What**:
* Updated `peerDependencies` to allow Cypress 3
* Updated Cypress within the `devDependencies`
* Updated serve within the `devDependencies`
* Changed configs and scripts accordingly.
**Checklist**:
Locally, I'm having an issue with `npm run validate` not exiting. Everything passes, but the process doesn't exit. Curious to see if it also happens in Travis.
=> chore(deps): Allow Cypress 3 within peerDep. Updated Cypress and serve deps

jest.config.js, package.json
**What**:
- Upgrade `dom-testing-library`
- Upgrade `serve`, mainly because it was printing a warning about a newer version.
- In the process I added a jest config setting without which I got weird errors. See [this](https://stackoverflow.com/a/51554619/621809) for details. Not sure why it has not been an issue for others so far.
**Why**:
The main motivation was upgrading `dom-testing-library` just to keep it up to date with the latest and greatest.
**How**:
By updating the dependency version numbers in `package.json`.
**Checklist**:
=> upgrade dom-testing-library

README.md
**What**:
Add link to Cypress in `README`.
**Why**:
Might be helpful for people that : 
- don't know what Cypress is. 
- are familiar with `kcd-testing-libraries` testing style but not Cypress.
- are looking for quick link to Cypress to browse docs.
**Checklist**:
Please feel free to ignore this PR for any reason !
Cheers !
=> docs: Add link to Cypress

package.json, typings/index.d.ts, typings/tsconfig.json, typings/tslint.json
**What**: Attempts to fix #12. I've only added support for `getByTestId` to ensure that I've done things correctly. I wonder if there's an easy way to keep up to date with `dom-testing-library`?
**Why**: For TypeScript support
**How**: Added a `typings` directory and added a reference to `package.json`.
I've tried to copy how cypress adds its own types for chainable methods and custom commands: https://github.com/cypress-io/add-cypress-custom-command-in-typescript/blob/master/README.md
**Checklist**:
=> WIP: chore(typescript): add TypeScript typings

typings/index.d.ts
These changes in typings were not done when changing the API from *ByValue to *ByDisplayValue 
Fixes https://github.com/testing-library/cypress-testing-library/issues/42
**What**: Change typings to resemble newer *ByDisplayValue API
**Why**: API introduced breaking changes that were not resembled in typings of this project
**How**: by changing the typings to match the correct function names
**Checklist**:
=> Adjust *ByValue to *ByDisplayValue

README.md
Edited README only.
Why?
I followed the instructions and it didn't work with recent changes to official instructions from Cypress-typescript I installed last week. So these documentation will help out anyone doing this today.
I also found the types file to be handy for all library definitions, so I added it into the README
=> 📝 Add correct README instructions for tsconfig

package.json, tests/typescript-types/test.spec.ts, typings/index.d.ts
Without this fix, the types are wrong using methods like `invoke` or using callbacks on commands.
Fixes #39.
Supercedes #40.
Thanks to @simenbrekken for doing the initial work on this!
**Checklist**:
=> fix(TS): Cypress commands return jQuery objects

README.md
Hey there, thanks for this library! Just ran across it now.
Just a quick PR to update the casing of TypeScript.
**What**:
Casing for "TypeScript" has been updated.
**Why**:
It was lowercase.
**Checklist**:
=> Fix TypeScript casing

tests/typescript-types/test.spec.ts, typings/index.d.ts
Some functions have not the right typings. I started from the `getByLabelText` function to discover that the bug affects all the following functions
```
getByAltText
getByDisplayValue
getByLabelText
getByRole
getBySelectText
getByTestId
getByText
getByTitle
```
@aaronmcadam (partially) fixed it in #56 but the functions above were left untouched. @aaronmcadam I'm not sure why you have not fixed the above functions too. 
**Why**:
Because you can not consume the `getByLabelText` etc. functions with the right/expected flow
**How**:
To be sure that I'm making the correct thing I proceeded this way:
- accordingly to the actual typing, the above functions should return standard HTML elements, I've asserted that adding
```javascript
.then($el => {
expect(Cypress.dom.isJquery($el)).to.eq(false); …
```
=> fix(TS): Cypress commands return jQuery objects (#58)

package.json
Updated the package version of @testing-library/dom
**What**:
Increased the minimum version of the @testing-library/dom dependency for the project
**Why**:
To ensure we Cypress related fixes for setImmediate are included when being used
**How**:
Updated package.json
**Checklist**:
=> Ensure higher version of dom is used

.travis.yml, cypress/integration/commands.spec.js
Build was broken due to linting error:
```bash
[lint] 
[lint] /home/travis/build/testing-library/cypress-testing-library/cypress/integration/commands.spec.js
[lint]   43:5  error  Promise should be returned to test its fulfillment or rejection  jest/valid-expect-in-promise
[lint] 
[lint] ✖ 1 problem (1 error, 0 warnings)
```
=> Fix broken build

src/index.js
**What**:
We should be able to configure the library [using the same `configure` function as provided by `@testing-library/dom`](https://testing-library.com/docs/dom-testing-library/api-configuration).
**Why**:
I'm currently working at an organisation in which the components all use a custom test id attribute.
**How**:
I exported `@testing-library/dom#configure` from the `index.js`.
**Checklist**:
=> Expose @testing-library/dom#configure to support configuring the `testIdAttribute`

README.md
**What**: The README.md was outdated with the `cy.get(All)By*` commands that were removed and replaced with an error in favor of `cy.find(All)By*`.
**Why**: Just to make documentation and use more clear for users of the repo.
**How**: README.md updates
**Checklist**:
~- [ ] Tests~
If y'all would like I can open up an issue on testing-library docs for someone else to grab and reference this one so they can get an OSS contribution.
=> Update README.md to coincide with 5.0 release

README.md
Hi 👋 ,
Thank you for your work 👍 
**What**:
There is a broken link in the usage section.
**Why**:
The test file doesn't exist anymore.
**How**:
I changed the old link into two links pointing to the find and query test files.
**Checklist**:
=> docs: Fix broken link to tests in usage section

src/index.js
**What**:
Fixes #89 and maybe #37 
**Why**:
There was a regression in ab5263d that removed the timeout from the promise chain.
**How**:
I reintroduced the timeout.
**Checklist**:
=> Reintroduce timeout on the outer command then chain

cypress/integration/find.spec.js, src/__tests__/add-commands.js, src/add-commands.js, src/index.js
**What**:
Changes the custom Cypress commands to respect the previously yielded subject, for example, with the following document:
```html
<button>Button Text 1</button>
<div id="nested">
<button>Button Text 2</button>
</div>
```
this
```js
cy.get('#nested').findByText('Button Text 1').should('not.exist')
```
would previously fail because `findByText` was not passed the result of `cy.get('#nested')` as its `container` (defaulting to `document`)
**Why**:
It's a convenient way to scope commands to the result of a previous command, and for users of builtin Cypress commands it's surprising that `@testing-library/cypress` doesn't currently behave like this.
**How**:
The [`prevSubject` option](https://docs.cypress.io/api/cypress-api/custom-commands.html#Usage) is now passed to …
=> Support running commands against the previous yielded subject

cypress.json, cypress/fixtures/test-app/index.html, cypress/integration/find.spec.js, cypress/integration/get.spec.js, cypress/integration/query.spec.js, package.json
**What**:
Removing `wait-on` and `serve` as dependencies
**Why**:
Cypress starts it's own server. The `fixtures` file can be accessed by `cy.visit('cypress/fixtures')`. This simplifies the dev experience by not requiring a web server to be maintained or risk port collisions.
**How**:
Removed dependencies, updated scripts and updated URLs called in test files and HTML files
**Checklist**:
New formatting must have been added as a pre-commit hook. I disabled them to avoid a noisy pull request
=> chore: remove uneeded dependencies and simplify setup

cypress/integration/get.spec.js, src/index.js
Related to #103
**What**:
Removing extra log message for `get*` queries.
Before:
After:
**Why**:
It isn't really a big deal, but it is a bit distracting seeing the log message multiple times - once as a spinner (Cypress thinks the log is still pending because the error prevented it from closing) and once as an error line.
**How**:
I removed the `Cypress.log`. Logs usually need an `.end()` to tell Cypress when the log is closed since Cypress commands are asynchronous. Cypress is already logging errors in commands for us, so we don't need to log as well.
**Checklist**:
=> fix: remove extra command log message for get* queries

README.md, cypress/.eslintrc, cypress/fixtures/test-app/index.html, cypress/integration/find.spec.js, cypress/integration/query.spec.js, package.json, src/__tests__/add-commands.js, src/add-commands.js, src/index.js
**Why**:
I'm a big fan of the React Testing Library and the concept behind it. I wanted those concepts to come to `@testing-library/cypress` as well, but the commands didn't do what I expected. It wasn't even until recently that #100 allowed a previous subject to be used! These commands are just too useful, but just lacked the last mile of finesse. Most of these issues are outlined in #103 
This PR closes some of the UX/DX gaps that built-in Cypress commands have.
My original intent was to break features up into separate PRs, but the features required changes to the same lines of code and could not be done independently. If it is a big concern, features can be introduced in separate PRs serially due to the interdependency of the same lines of code.
**What**:
* Add element selector …
=> feat: add more helpful debugging information to queries

cypress/fixtures/test-app/index.html, cypress/integration/find.spec.js, src/index.js
**What**:
Allow commands to be chained when previous command does not returns document, element or window
**Why**:
Fix #114 
**How**:
Remove document, element or window from `prevSubject` in `createCommand`
**Checklist**:
=> Fix chain commands with previous subject different of document, element or window

add-commands.js
**What**: Outdated comment in source code
**Why**: The comment referenced an outdated library
**Checklist**:
=> chore: update comment in add-commands

cypress/integration/query.spec.js, src/index.js
Fixes #117
**Checklist**:
This PR is overdue. I had the fix for a while, but sat on it too long. If you read up on #117, you'll see the person who filed the bug no longer has the issue. This PR does revert the `query*` functionality to what it was previously. The functionality difference is subtle, but I'll explain it here:
After #108, `query*` was subtly changed to have the same functionality as `find*` queries, but with no retries. This changed the error messages (they were more helpful), but also changed the way the command worked which would break in this circumstance:
```js
cy.queryByText('Never Exists').then(val => {
cy.wrap(val).should('not.exist')
})
```
Before the `cy.queryByText('Never Exists')` would return `null` and the test would pass. After, the `cy.queryByText('Never …
=> chore: add deprecation warning to query*

README.md
=> Update README with JS intellisense instructions

.eslintrc, cypress/.eslintrc, cypress/integration/find.spec.js
* DOM Testing Library changed an error message when multiple DOM nodes are found, so the test was updated to look for a smaller subset of the error. We don't have control over the error message, but want to make sure the right one was thrown.
* Testing Library added more linting rules that don't make sense in the context of Cypress Testing Library, so these lint rules have been disabled to not confuse contributors.
**Checklist**:
=> fix: Fix ESLint config and failing test

types/index.d.ts, types/test.ts
**What**:
Fixes `cy.configureCypressTestingLibrary(config)` for TypeScript users. Fixes #143.
Also, ran `prettier` for the changed files.
**Why**:
Type safety. 🎉
**How**:
I've added a declaration for `configureCypressTestingLibrary` in the type definitions.
**Checklist**:
=> Fix configureCypressTestingLibrary typings

package.json
**What**:
Update for new release: https://docs.cypress.io/guides/references/changelog.html#6-0-0
**Why**:
To avoid peer dep warnings when installing
**How**:
GH editor. I also tested with cypress v6 at work
**Checklist**:
=> fix: allow cypress@6 in peer dependencies

types/index.d.ts
**What**:
Fix  findByRole() and findAllByRole() type definition to check role name as same as upstream @testing-library/dom does.
**Why**:
Current type definition uses Matcher type this is for jQuery selector.
**How**:
Switch role name type to ByRoleMatcher that is used in @testing-library/dom.
**Checklist**:
I confirmed VSCode shows role names in completion word list.
=> Fix findByRole() and findAllByRole() type definition to check role name

package.json
**What**:
To not have a peer dep warning when installing
**Why**:
https://github.com/cypress-io/cypress/releases/tag/v7.0.0
**How**:
GH Editor
**Checklist**:
=> fix: allow cypress@v7 in peer dependency range

.github/workflows/validate.yml, CONTRIBUTING.md, README.md, other/MAINTAINING.md
-->
as Git announced that main  should be your primary branch, I'm renaming all master references to main
**What**:
**Why**:
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)
=> chore: rename proj. from master to main

CONTRIBUTING.md
**What**: 
Update links (e.g. egghead.io link redirects to some old preview page for their newly launched site).
**Why**:
It could be confusing for first-time contributors (like me) 😄 
**How**:
Searched for the correct links:
OLD: https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github
NEW: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
Replaced old references to `kentcdodds` repo with the new one `testing-library` (even though the redirects seem to work fine)
**Checklist**:
It might also be something to check the other repositories if they have the same outdated links. 🤔
=> docs(CONTRIBUTING): update links

types/index.d.ts
**What**:
Add `log?: boolean` to the options of all commands.
**Why**:
This is already supported at runtime:
https://github.com/testing-library/cypress-testing-library/blob/03b0309dc8d5e4d13b9307baa89a16aaa2ba9419/src/index.js#L21-L26
**How**:
Just edited the correct `.d.ts` and checked this change in my project.
**Checklist**:
=> Add Loggable to accepted options of commands since it works at runtime

package.json
**What**:
Bumps the `@testing-library/dom` version to `^7.29.6`
**Why**:
Currently when using the `expanded` option in `cy.findByRole` Typescript complains that `expanded` is not defined in the `ByRoleOptions` type. 
Example:
```javascript
cy.findByRole("button", {
name: /button-label/i,
expanded: true, // the expanded prop is not allowed by typescript
})
```
This is because the `@testing-library/dom v7.28.1` that's being referenced in `package.json` doesn't have the `expanded` property defined in `queries.d.ts`
**How**:
I've updated the `@testing-library/dom` version in `package.json`
**Checklist**:
The version of `@testing-library/dom` went from `7.28.1` -> `7.29.6`, the most significant change between those versions was adding types I think.
I'd like to try it out in one of my own …
=> Update @testing-library/dom version

cypress/integration/find.spec.js, src/utils.js
**What**:
This PR updates the `getContainer` util to only fallback to the `withinSubject` if an explicit subject has not been yielded by the previous command.
**Why**:
The following code fails without this change:
```html
<section>
<button>Button Text 1</button>
<div id="nested">
<button>Button Text 2</button>
</div>
</section>
```
```js
cy.get('section').within(() => {
cy.get('#nested').findByText(/Button Text/).should('exist');
});
```
**How**:
I cloned the repo, added a new test case that failed, and then updated the util to fix the new test.
**Checklist**:
=> Fixes #201: stop ignoring current subject when inside a .within

.npmrc
Following https://github.com/testing-library/react-testing-library/pull/975
**Why**:
```
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect.
```
**Checklist**:
=> chore: set protocol for npm to `https`

types/index.d.ts
**What**: Docs update
**Why**: Typo
**How**: Fixed typo
**Checklist**:
=> chore: fix typo in findAllBy inline docs

src/index.js
=> fix: update Cypress' log bar with timeout information

cypress/e2e/find.cy.js, package.json
**What**:
Updating testing-library-dom to the latest version
**Why**:
There were breaking changes in 8->9. Adding this library broke most of our existing jest tests because it requires `testing-library-dom^8.2.1`, but the latest `testing-library-react` requires `testing-library-dom^9.0.0`
**How**:
Updates the dependency and fixes a test failure caused by one of the breaking changes in testing-library-dom
**Checklist**:
=> fix: update testing-libary-dom to 9

src/index.js
**What**:
This fixes a bug where `this.get('prev')` returns undefined in some scenarios and the command `this.get('prev').get('chainerId')` throws an error since it's attempting to read `get` of `undefined`.
**Why**:
There is more information about this issue here: https://github.com/testing-library/cypress-testing-library/issues/248, but several people have commented that they are experiencing this. @matt-vendia responded with a solution on that issue, which solves the problem for me too (along with others who thumbs-upped the comment).
**How**:
Make sure `this.get('prev')` exists before assuming it's an object.
**Checklist**:
This change is safe and small enough that it is ready to be merged imo.
=> Fix bug with cypress `testIsolation` option

package.json
**What**: This adds Cypress 14 to the peer dependency and dev dependencies of this project.
**Why**: The peer dependency change ensures that we can install Cypress 14 with npm without resorting to --legacy-peer-deps. The devDependencies change makes sure that we are actually testing against Cypress 14 and not a lower version.
**How**: I changed the numbers in the package.json, ran `npm i` and `npm run validate`. 
**Checklist**:
Close #280
=> fix(deps): update cypress to version 14.0.0 and adjust peer dependencies

.github/workflows/validate.yml, package.json
Adds support for Cypress 15, which released on August 20th, 2025
**What**:
**Why**:
**How**:
**Checklist**:
=> feat: support Cypress 15

.github/workflows/validate.yml
**What**:
Update action versions:
| From                                                                                               | To                                                                                                 | `runs.using` |
| -------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- | ------------ |
| [actions/checkout@v2](https://github.com/actions/checkout/tree/v2)                                 | [actions/checkout@v5](https://github.com/actions/checkout/tree/v5)                                 | `node24`     |
| [actions/setup-node@v2](https://github.com/actions/setup-node/tree/v2)                             | …
=> ci: update validate workflow versions
